ID: 1287
Title: [Bug]: sqlalchem+pymysql connect ob error
Description:
### Please check the issue list for the same bug

- [X] Please checked issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
- OB  V3.1.2,  python V3.10, sqlalchemy V1.4.39 pymysql V1.0.2
- Hardware parameter: Windows 10 Enterprise
```


### Fast Reproduce Steps(Required)


```python
import sqlalchemy
engine = sqlalchemy.create_engine(
    'mysql+pymysql://xxxxxxx@xxx.xxxxxxx:2881/xxx?charset=xxxx',
    pool_size=50, pool_recycle=20)

engine.connect()

```


### Actual Behavior

Traceback (most recent call last):
  File "C:\Users\jackma\PycharmProjects\connect.py", line 28, in <module>
    engine.connect()
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\engine\base.py", line 3234, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\engine\base.py", line 96, in __init__
    else engine.raw_connection()
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\engine\base.py", line 3313, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\engine\base.py", line 3280, in _wrap_pool_connect
    return fn()
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\pool\base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\pool\base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\pool\base.py", line 476, in checkout
    rec = pool._do_get()
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\pool\impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\pool\impl.py", line 143, in _do_get
    return self._create_connection()
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\pool\base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\pool\base.py", line 371, in __init__
    self.__connect()
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\pool\base.py", line 679, in __connect
    )._exec_w_sync_on_first_run(self.dbapi_connection, self)
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\event\attr.py", line 329, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\event\attr.py", line 343, in __call__
    fn(*args, **kw)
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\engine\create.py", line 686, in first_connect
    dialect.initialize(c)
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\dialects\mysql\base.py", line 2716, in initialize
    default.DefaultDialect.initialize(self, connection)
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\engine\default.py", line 420, in initialize
    self.default_isolation_level = self.get_default_isolation_level(
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\engine\default.py", line 486, in get_default_isolation_level
    return self.get_isolation_level(dbapi_conn)
  File "D:\Anaconda3\envs\jackma\lib\site-packages\sqlalchemy\dialects\mysql\base.py", line 2453, in get_isolation_level
    if self._is_mysql and self.server_version_info >= (5, 7, 20):
TypeError: '>=' not supported between instances of 'NoneType' and 'tuple'

### Expected Behavior

_No response_

### other information

_No response_