{
    "sql": "CREATE TABLE part1_local (id Int32, id2 Int32 ALIAS id) ENGINE=Memory; CREATE TABLE part2_local AS part1_local ENGINE=Memory; CREATE TABLE merge_local (id Int32, id2 Int32) ENGINE=Merge(currentDatabase(), '^part.+_local$'); CREATE TABLE part1_all AS part1_local ENGINE=Distributed('cluster01', currentDatabase(), part1_local, rand()); CREATE TABLE part2_all AS part1_local ENGINE=Distributed('cluster01', currentDatabase(), part2_local, rand()); CREATE TABLE merge_all (id Int32, id2 Int32) ENGINE=Merge(currentDatabase(), '^part.+_all$'); INSERT INTO part1_local VALUES (1); INSERT INTO part2_local VALUES (2); SELECT id, id2 FROM merge_all;",
    "Affected Elements": "SELECT statement, Merge engine, Distributed table",
    "Root Cause Analysis": "The `merge_all` table does not correctly reference the alias `id2` from the distributed tables due to how the Merge engine processes columns, leading to the error that the column `id2` cannot be found."
}